### ISSUE TITLE
When protected with Fire Protection armor heat damage still "shows" via visual/audio

### ISSUE THREAD

**Issue by pete-h** [Sparkierkan7/thermite_mod#2]
When in the nether and beeing protected with Fire Prod IV armor, damage is applied about every 4 or 5 "cycle" (which is intended behaviour, correct?)

But even when I don't receive the overheating damage, I have the damage sound and the damage "jerk". Is this intended?
It quite confusing to "see and hear" damage, but not to receive it.

**Comment by Sparkierkan7** [comment]
Ok so i think whats happening is the game thinks your taking damage from being on fire because the source of the hyperthermia damage is set to the same source as fire damage is. So the fire protection enchantment is stopping some of the damage just as if you were on fire. If you set yourself on fire with fire protection you should still have the damage tilt and audio even if you take no damage.

I might make it so fire protection cools you a bit just like leather armor warms you.

**Comment by pete-h** [comment]
I like the idea with fire prod cooling you off a bit :)

**Comment by Sparkierkan7** [comment]
Ok i think i will make fire prot cool you down in a future update.
